# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "timers"
gem "colorize"
gem "artii"
gem "tty-prompt"
gem "rspec"